/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Detail */
        get: operations["get_task_detail_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/actions/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Action */
        post: operations["run_action_tasks__task_id__actions_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/actions/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Action */
        post: operations["pause_action_tasks__task_id__actions_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/phases/{phase}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Phase Runs */
        get: operations["get_phase_runs_tasks__task_id__phases__phase__get"];
        /**
         * Update Phase
         * @description Manual override for a phase's output.
         *
         *     Per spec §1: human edits never bypass QA — this saves a new PhaseRun with
         *     edited_by_human=True flag, then re-runs the gates against the edited output.
         *     The caller can choose to skip QA only by also calling /qa themselves with
         *     different content.
         */
        put: operations["update_phase_tasks__task_id__phases__phase__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/phases/{phase}/qa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rerun Qa
         * @description Re-run QA gates against the latest passed output of a phase, without
         *     re-generating. Useful after schema/judge changes to validate prior outputs.
         */
        post: operations["rerun_qa_tasks__task_id__phases__phase__qa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Task
         * @description Bundle the publishable artefacts (Video JSON + titles/description/pinned)
         *     plus a few headline metadata fields. Works on tasks in any state — exports
         *     whatever passed phases produced; missing phases come back as null.
         */
        get: operations["export_task_tasks__task_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/fork/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fork */
        post: operations["fork_eval_fork__task_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_eval_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch */
        post: operations["batch_eval_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/task/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Eval Task
         * @description Convenience endpoint used by the CLI to resolve fork outputs.
         */
        get: operations["get_eval_task_eval_task__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Audience
         * @enum {string}
         */
        Audience: "学生" | "从业者" | "决策者";
        /** BatchRequest */
        BatchRequest: {
            /** Source Pack Path */
            source_pack_path?: string | null;
            /** Source Pack Content */
            source_pack_content?: string | null;
            /**
             * Title
             * @default eval batch
             */
            title: string;
            /** Models */
            models: string[];
            /**
             * Opening Styles
             * @default [
             *       "auto"
             *     ]
             */
            opening_styles: components["schemas"]["OpeningStyle"][];
            /**
             * Run Async
             * @default true
             */
            run_async: boolean;
        };
        /** BatchResponse */
        BatchResponse: {
            /** Task Ids */
            task_ids: string[];
        };
        /** CompareResponse */
        CompareResponse: {
            comparison: components["schemas"]["TaskComparison"];
            /** Config Diff */
            config_diff: {
                [key: string]: unknown;
            };
        };
        /** CreateTaskRequest */
        CreateTaskRequest: {
            /** Title */
            title: string;
            source: components["schemas"]["SourceInput"];
            config?: components["schemas"]["TaskConfig"] | null;
            /**
             * Run Async
             * @default false
             */
            run_async: boolean;
        };
        /**
         * ExportFormat
         * @enum {string}
         */
        ExportFormat: "landscape" | "portrait" | "square";
        /** ForkRequest */
        ForkRequest: {
            /**
             * Title Suffix
             * @default fork
             */
            title_suffix: string;
            /** Llm Model */
            llm_model?: string | null;
            /** Llm Provider */
            llm_provider?: string | null;
            opening_style?: components["schemas"]["OpeningStyle"] | null;
            /**
             * Run Immediately
             * @default true
             */
            run_immediately: boolean;
            /**
             * Run Async
             * @default false
             */
            run_async: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OpeningStyle
         * @enum {string}
         */
        OpeningStyle: "judgment_first" | "suspense_first" | "auto";
        /**
         * PhaseId
         * @enum {string}
         */
        PhaseId: "P1" | "P1.5" | "P2" | "P2.5" | "P2.6" | "P3" | "P4" | "P5" | "P6" | "P0" | "P7";
        /** PhaseRun */
        PhaseRun: {
            /** Id */
            id: string;
            /** Task Id */
            task_id: string;
            phase_id: components["schemas"]["PhaseId"];
            /**
             * Attempt
             * @default 1
             */
            attempt: number;
            /**
             * Trigger
             * @default auto
             * @enum {string}
             */
            trigger: "auto" | "manual_resume" | "manual_qa_rerun";
            /** Llm Provider */
            llm_provider: string;
            /** Llm Model */
            llm_model: string;
            /** Output */
            output: {
                [key: string]: unknown;
            };
            qa_result?: components["schemas"]["QAResult"] | null;
            status: components["schemas"]["PhaseRunStatus"];
            /**
             * Edited By Human
             * @default false
             */
            edited_by_human: boolean;
            /** Edit Note */
            edit_note?: string | null;
            cost?: components["schemas"]["TokenUsage"];
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * PhaseRunStatus
         * @enum {string}
         */
        PhaseRunStatus: "passed" | "qa_failed" | "qa_failed_terminal" | "error";
        /** QAGate */
        QAGate: {
            /** Gate Id */
            gate_id: string;
            /** Name */
            name: string;
            /** Passed */
            passed: boolean;
            /** Rationale */
            rationale: string;
            /** Evidence */
            evidence?: unknown | null;
        };
        /** QAResult */
        QAResult: {
            /** Gates */
            gates: components["schemas"]["QAGate"][];
            /** Passed Overall */
            passed_overall: boolean;
        };
        /** SourceInput */
        SourceInput: {
            /** Pack Path */
            pack_path?: string | null;
            /** Pack Content */
            pack_content?: string | null;
        };
        /** Task */
        Task: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            source: components["schemas"]["SourceInput"];
            config: components["schemas"]["TaskConfig"];
            /** @default P1 */
            current_phase: components["schemas"]["PhaseId"];
            /** @default running */
            status: components["schemas"]["TaskStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TaskComparison
         * @description Side-by-side comparison of two tasks (typically a fork of the same source pack).
         */
        TaskComparison: {
            /** A Id */
            a_id: string;
            /** B Id */
            b_id: string;
            /** A Config */
            a_config: {
                [key: string]: unknown;
            };
            /** B Config */
            b_config: {
                [key: string]: unknown;
            };
            a_status: components["schemas"]["TaskStatus"];
            b_status: components["schemas"]["TaskStatus"];
            /** A Total Duration Ms */
            a_total_duration_ms: number;
            /** B Total Duration Ms */
            b_total_duration_ms: number;
            /** A Total Input Tokens */
            a_total_input_tokens: number;
            /** B Total Input Tokens */
            b_total_input_tokens: number;
            /** A Total Output Tokens */
            a_total_output_tokens: number;
            /** B Total Output Tokens */
            b_total_output_tokens: number;
            /** Phase Summary */
            phase_summary: {
                [key: string]: unknown;
            }[];
        };
        /** TaskConfig */
        TaskConfig: {
            /** @default 决策者 */
            target_audience: components["schemas"]["Audience"];
            /**
             * Target Tier
             * @default auto
             */
            target_tier: components["schemas"]["Tier"] | "auto";
            /**
             * Export Formats
             * @default auto
             */
            export_formats: components["schemas"]["ExportFormat"][] | "auto";
            /** @default auto */
            opening_style: components["schemas"]["OpeningStyle"];
            /** Llm Provider */
            llm_provider?: string;
            /** Llm Model */
            llm_model?: string;
            /** Qa Max Retries */
            qa_max_retries?: {
                [key: string]: number;
            };
            /**
             * Enable Topic Validation
             * @default false
             */
            enable_topic_validation: boolean;
            /**
             * Enable Commercial Alignment
             * @default false
             */
            enable_commercial_alignment: boolean;
            /**
             * Enable Cognition Gap Check
             * @default false
             */
            enable_cognition_gap_check: boolean;
        };
        /** TaskDetail */
        TaskDetail: {
            task: components["schemas"]["Task"];
            /** Runs */
            runs: components["schemas"]["PhaseRun"][];
        };
        /** TaskExport */
        TaskExport: {
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Video Json */
            video_json?: {
                [key: string]: unknown;
            } | null;
            /** Publishing */
            publishing?: {
                [key: string]: unknown;
            } | null;
            /** Judgment */
            judgment?: string | null;
            /** Theme */
            theme?: string | null;
            /** Tier */
            tier?: string | null;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "running" | "paused_for_human" | "completed" | "failed";
        /**
         * Tier
         * @enum {string}
         */
        Tier: "引流" | "留存" | "转化";
        /** TokenUsage */
        TokenUsage: {
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Cached Input Tokens
             * @default 0
             */
            cached_input_tokens: number;
            /**
             * Estimated Cost Usd
             * @default 0
             */
            estimated_cost_usd: number;
        };
        /** UpdatePhaseRequest */
        UpdatePhaseRequest: {
            /** Output */
            output: {
                [key: string]: unknown;
            };
            /**
             * Edit Note
             * @default
             */
            edit_note: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tasks_tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_detail_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_action_tasks__task_id__actions_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_action_tasks__task_id__actions_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_phase_runs_tasks__task_id__phases__phase__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                phase: components["schemas"]["PhaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhaseRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_phase_tasks__task_id__phases__phase__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                phase: components["schemas"]["PhaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePhaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhaseRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerun_qa_tasks__task_id__phases__phase__qa_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                phase: components["schemas"]["PhaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhaseRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_task_tasks__task_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskExport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fork_eval_fork__task_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_eval_compare_get: {
        parameters: {
            query: {
                a: string;
                b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_eval_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_task_eval_task__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
